class Personaje {
    constructor(id, nombre, imagen, ...atributos) {
        this.id = id;
        this.nombre = nombre;
        this.imagen = imagen;
        this.atributos = atributos;
    }
}

const characters = [
    {
        id: 0,
        nombre: "Iron Man",
        imagen: "./Recursos/Personajes/ironman.png",
        atributos: {
            esHumano: true,
            esExtraterrestre: false,
            esRobot: false,
            esHombre: true,
            tienePoderesSobrenaturales: false,
            tieneHabilidadesTecnologicas: true,
            pielNoHumana: false,
            pielMorena: false,

            barbaBigote: true,
            cabelloLargo: false,
            calvo: false,
            llevaCasco: true,
            llevaCapa: false,
            trajeMetalico: true,
            alas: false,
            ropaNegra: false,
            esVengador: true,
            SpiderMan: false,
            esGuardianGalaxia: false,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 1,
        nombre: "Capitan América",
        imagen: "./Recursos/Personajes/capitan_america.png",
        atributos: {
            esHumano: true,
            esExtraterrestre: false,
            esRobot: false,
            esHombre: true,
            tienePoderesSobrenaturales: true,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: false,
            pielMorena: false,

            barbaBigote: false,
            cabelloLargo: false,
            calvo: false,
            llevaCasco: false,
            llevaCapa: false,
            trajeMetalico: false,
            alas: false,
            ropaNegra: false,
            esVengador: true,
            SpiderMan: false,
            esGuardianGalaxia: false,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 2,
        nombre: "Groot",
        imagen: "./Recursos/Personajes/groot.jpeg",
        atributos: {
            esHumano: false,
            esExtraterrestre: true,
            esRobot: false,
            esHombre: true,
            tienePoderesSobrenaturales: true,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: true,
            pielMorena: false,

            barbaBigote: false,
            cabelloLargo: false,
            calvo: false,
            llevaCasco: false,
            llevaCapa: false,
            trajeMetalico: false,
            alas: false,
            ropaNegra: false,
            esVengador: false,
            SpiderMan: false,
            esGuardianGalaxia: true,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 3,
        nombre: "Thor",
        imagen: "./Recursos/Personajes/thor.png",
        atributos: {
            esHumano: false,
            esExtraterrestre: true,
            esRobot: false,
            esHombre: true,
            tienePoderesSobrenaturales: true,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: false,
            pielMorena: false,

            barbaBigote: true,
            cabelloLargo: true,
            calvo: false,
            llevaCasco: false,
            llevaCapa: true,
            trajeMetalico: false,
            alas: false,
            ropaNegra: false,
            esVengador: true,
            SpiderMan: false,
            esGuardianGalaxia: false,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 4,
        nombre: "Hulk",
        imagen: "./Recursos/Personajes/hulk.webp",
        atributos: {
            esHumano: true,
            esExtraterrestre: false,
            esRobot: false,
            esHombre: true,
            tienePoderesSobrenaturales: true,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: true,
            pielMorena: false,

            barbaBigote: false,
            cabelloLargo: false,
            calvo: false,
            llevaCasco: false,
            llevaCapa: false,
            trajeMetalico: false,
            alas: false,
            ropaNegra: false,
            esVengador: true,
            SpiderMan: false,
            esGuardianGalaxia: false,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 5,
        nombre: "Viuda Negra",
        imagen: "./Recursos/Personajes/viuda_negra.png",
        atributos: {
            esHumano: true,
            esExtraterrestre: false,
            esRobot: false,
            esHombre: false,
            tienePoderesSobrenaturales: false,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: false,
            pielMorena: false,

            barbaBigote: false,
            cabelloLargo: true,
            calvo: false,
            llevaCasco: false,
            llevaCapa: false,
            trajeMetalico: false,
            alas: false,
            ropaNegra: true,
            esVengador: true,
            SpiderMan: false,
            esGuardianGalaxia: false,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 6,
        nombre: "Hawk Eye",
        imagen: "./Recursos/Personajes/hawk_eye.jpg",
        atributos: {
            esHumano: true,
            esExtraterrestre: false,
            esRobot: false,
            esHombre: true,
            tienePoderesSobrenaturales: false,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: false,
            pielMorena: false,

            barbaBigote: false,
            cabelloLargo: false,
            calvo: false,
            llevaCasco: false,
            llevaCapa: false,
            trajeMetalico: false,
            alas: false,
            ropaNegra: false,
            esVengador: true,
            SpiderMan: false,
            esGuardianGalaxia: false,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 7,
        nombre: "Vision",
        imagen: "./Recursos/Personajes/vision.png",
        atributos: {
            esHumano: false,
            esExtraterrestre: false,
            esRobot: true,
            esHombre: true,
            tienePoderesSobrenaturales: false,
            tieneHabilidadesTecnologicas: true,
            pielNoHumana: true,
            pielMorena: false,

            barbaBigote: false,
            cabelloLargo: false,
            calvo: true,
            llevaCasco: false,
            llevaCapa: true,
            trajeMetalico: false,
            alas: false,
            ropaNegra: false,
            esVengador: true,
            SpiderMan: false,
            esGuardianGalaxia: false,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 8,
        nombre: "Dr Strange",
        imagen: "./Recursos/Personajes/dr_strange.jpg",
        atributos: {
            esHumano: true,
            esExtraterrestre: false,
            esRobot: false,
            esHombre: true,
            tienePoderesSobrenaturales: true,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: false,
            pielMorena: false,

            barbaBigote: true,
            cabelloLargo: false,
            calvo: false,
            llevaCasco: false,
            llevaCapa: true,
            trajeMetalico: false,
            alas: false,
            ropaNegra: false,
            esVengador: true,
            SpiderMan: false,
            esGuardianGalaxia: false,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 9,
        nombre: "Pantera Negra",
        imagen: "./Recursos/Personajes/pantera_negra.png",
        atributos: {
            esHumano: true,
            esExtraterrestre: false,
            esRobot: false,
            esHombre: true,
            tienePoderesSobrenaturales: false,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: false,
            pielMorena: true,

            barbaBigote: true,
            cabelloLargo: false,
            calvo: false,
            llevaCasco: true,
            llevaCapa: false,
            trajeMetalico: false,
            alas: false,
            ropaNegra: true,
            esVengador: true,
            SpiderMan: false,
            esGuardianGalaxia: false,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 10,
        nombre: "Ant-Man",
        imagen: "./Recursos/Personajes/antman.png",
        atributos: {
            esHumano: true,
            esExtraterrestre: false,
            esRobot: false,
            esHombre: true,
            tienePoderesSobrenaturales: false,
            tieneHabilidadesTecnologicas: true,
            pielNoHumana: false,
            pielMorena: false,

            barbaBigote: true,
            cabelloLargo: false,
            calvo: false,
            llevaCasco: true,
            llevaCapa: false,
            trajeMetalico: true,
            alas: false,
            ropaNegra: false,
            esVengador: true,
            SpiderMan: false,
            esGuardianGalaxia: false,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 11,
        nombre: "Star Lord",
        imagen: "./Recursos/Personajes/starlord.png",
        atributos: {
            esHumano: true,
            esExtraterrestre: false,
            esRobot: false,
            esHombre: true,
            tienePoderesSobrenaturales: false,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: false,
            pielMorena: false,

            barbaBigote: true,
            cabelloLargo: false,
            calvo: false,
            llevaCasco: true,
            llevaCapa: false,
            trajeMetalico: false,
            alas: false,
            ropaNegra: false,
            esVengador: false,
            SpiderMan: false,
            esGuardianGalaxia: true,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 12,
        nombre: "Gamora",
        imagen: "./Recursos/Personajes/gamora.png",
        atributos: {
            esHumano: false,
            esExtraterrestre: true,
            esRobot: false,
            esHombre: false,
            tienePoderesSobrenaturales: true,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: true,
            pielMorena: false,

            barbaBigote: false,
            cabelloLargo: true,
            calvo: false,
            llevaCasco: false,
            llevaCapa: false,
            trajeMetalico: false,
            alas: false,
            ropaNegra: true,
            esVengador: false,
            SpiderMan: false,
            esGuardianGalaxia: true,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 13,
        nombre: "Drax",
        imagen: "./Recursos/Personajes/drax.jpg",
        atributos: {
            esHumano: false,
            esExtraterrestre: true,
            esRobot: false,
            esHombre: true,
            tienePoderesSobrenaturales: true,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: true,
            pielMorena: false,

            barbaBigote: false,
            cabelloLargo: false,
            calvo: true,
            llevaCasco: false,
            llevaCapa: false,
            trajeMetalico: false,
            alas: false,
            ropaNegra: false,
            esVengador: false,
            SpiderMan: false,
            esGuardianGalaxia: true,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 14,
        nombre: "Rocket",
        imagen: "./Recursos/Personajes/rocket.png",
        atributos: {
            esHumano: false,
            esExtraterrestre: true,
            esRobot: false,
            esHombre: true,
            tienePoderesSobrenaturales: true,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: true,
            pielMorena: false,

            barbaBigote: true,
            cabelloLargo: false,
            calvo: false,
            llevaCasco: false,
            llevaCapa: false,
            trajeMetalico: false,
            alas: false,
            ropaNegra: false,
            esVengador: false,
            SpiderMan: false,
            esGuardianGalaxia: true,
            esVillano: false,
            esAnimal: true,
            esJoven: false
        }
    },
    {
        id: 15,
        nombre: "Nebula",
        imagen: "./Recursos/Personajes/nebula.png",
        atributos: {
            esHumano: false,
            esExtraterrestre: true,
            esRobot: false,
            esHombre: false,
            tienePoderesSobrenaturales: false,
            tieneHabilidadesTecnologicas: true,
            pielNoHumana: true,
            pielMorena: false,

            barbaBigote: false,
            cabelloLargo: false,
            calvo: true,
            llevaCasco: false,
            llevaCapa: false,
            trajeMetalico: false,
            alas: false,
            ropaNegra: false,
            esVengador: false,
            SpiderMan: false,
            esGuardianGalaxia: true,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 16,
        nombre: "Mantis",
        imagen: "./Recursos/Personajes/mantis.png",
        atributos: {
            esHumano: false,
            esExtraterrestre: true,
            esRobot: false,
            esHombre: false,
            tienePoderesSobrenaturales: true,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: false,
            pielMorena: false,

            barbaBigote: false,
            cabelloLargo: true,
            calvo: false,
            llevaCasco: false,
            llevaCapa: false,
            trajeMetalico: false,
            alas: false,
            ropaNegra: false,
            esVengador: false,
            SpiderMan: false,
            esGuardianGalaxia: true,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 17,
        nombre: "Spider-Man",
        imagen: "./Recursos/Personajes/spiderman.jpg",
        atributos: {
            esHumano: true,
            esExtraterrestre: false,
            esRobot: false,
            esHombre: true,
            tienePoderesSobrenaturales: true,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: false,
            pielMorena: false,

            barbaBigote: false,
            cabelloLargo: false,
            calvo: false,
            llevaCasco: true,
            llevaCapa: false,
            trajeMetalico: false,
            alas: false,
            ropaNegra: false,
            esVengador: false,
            SpiderMan: true,
            esGuardianGalaxia: false,
            esVillano: false,
            esAnimal: false,
            esJoven: true
        }
    },
    {
        id: 18,
        nombre: "War Machine",
        imagen: "./Recursos/Personajes/war_machine.jpg",
        atributos: {
            esHumano: true,
            esExtraterrestre: false,
            esRobot: false,
            esHombre: true,
            tienePoderesSobrenaturales: false,
            tieneHabilidadesTecnologicas: true,
            pielNoHumana: false,
            pielMorena: true,

            barbaBigote: false,
            cabelloLargo: false,
            calvo: true,
            llevaCasco: true,
            llevaCapa: false,
            trajeMetalico: true,
            alas: false,
            ropaNegra: false,
            esVengador: true,
            SpiderMan: false,
            esGuardianGalaxia: false,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 19,
        nombre: "Falcón",
        imagen: "./Recursos/Personajes/falcon.jpg",
        atributos: {
            esHumano: true,
            esExtraterrestre: false,
            esRobot: false,
            esHombre: true,
            tienePoderesSobrenaturales: true,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: false,
            pielMorena: true,

            barbaBigote: false,
            cabelloLargo: false,
            calvo: true,
            llevaCasco: true,
            llevaCapa: false,
            trajeMetalico: false,
            alas: true,
            ropaNegra: false,
            esVengador: true,
            SpiderMan: false,
            esGuardianGalaxia: false,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 20,
        nombre: "Nick Furia",
        imagen: "./Recursos/Personajes/nick_furia.png",
        atributos: {
            esHumano: true,
            esExtraterrestre: false,
            esRobot: false,
            esHombre: true,
            tienePoderesSobrenaturales: false,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: false,
            pielMorena: true,

            barbaBigote: true,
            cabelloLargo: false,
            calvo: true,
            llevaCasco: false,
            llevaCapa: false,
            trajeMetalico: false,
            alas: false,
            ropaNegra: true,
            esVengador: true,
            SpiderMan: false,
            esGuardianGalaxia: false,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 21,
        nombre: "Winter Soldier",
        imagen: "./Recursos/Personajes/bucky_barnes.png",
        atributos: {
            esHumano: true,
            esExtraterrestre: false,
            esRobot: false,
            esHombre: true,
            tienePoderesSobrenaturales: true,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: false,
            pielMorena: false,

            barbaBigote: true,
            cabelloLargo: true,
            calvo: false,
            llevaCasco: false,
            llevaCapa: false,
            trajeMetalico: false,
            alas: false,
            ropaNegra: true,
            esVengador: true,
            SpiderMan: false,
            esGuardianGalaxia: false,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 22,
        nombre: "María Hill",
        imagen: "./Recursos/Personajes/maria_hill.png",
        atributos: {
            esHumano: true,
            esExtraterrestre: false,
            esRobot: false,
            esHombre: false,
            tienePoderesSobrenaturales: false,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: false,
            pielMorena: false,

            barbaBigote: false,
            cabelloLargo: false,
            calvo: false,
            llevaCasco: false,
            llevaCapa: false,
            trajeMetalico: false,
            alas: false,
            ropaNegra: true,
            esVengador: true,
            SpiderMan: false,
            esGuardianGalaxia: false,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 23,
        nombre: "Wong",
        imagen: "./Recursos/Personajes/wong.png",
        atributos: {
            esHumano: true,
            esExtraterrestre: false,
            esRobot: false,
            esHombre: true,
            tienePoderesSobrenaturales: true,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: false,
            pielMorena: true,

            barbaBigote: false,
            cabelloLargo: false,
            calvo: true,
            llevaCasco: false,
            llevaCapa: false,
            trajeMetalico: false,
            alas: false,
            ropaNegra: false,
            esVengador: true,
            SpiderMan: false,
            esGuardianGalaxia: false,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 24,
        nombre: "Okoye",
        imagen: "./Recursos/Personajes/okoye.png",
        atributos: {
            esHumano: true,
            esExtraterrestre: false,
            esRobot: false,
            esHombre: false,
            tienePoderesSobrenaturales: false,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: false,
            pielMorena: true,

            barbaBigote: false,
            cabelloLargo: false,
            calvo: true,
            llevaCasco: false,
            llevaCapa: false,
            trajeMetalico: false,
            alas: false,
            ropaNegra: false,
            esVengador: true,
            SpiderMan: false,
            esGuardianGalaxia: false,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 25,
        nombre: "Shuri",
        imagen: "./Recursos/Personajes/shuri.png",
        atributos: {
            esHumano: true,
            esExtraterrestre: false,
            esRobot: false,
            esHombre: false,
            tienePoderesSobrenaturales: false,
            tieneHabilidadesTecnologicas: true,
            pielNoHumana: false,
            pielMorena: true,

            barbaBigote: false,
            cabelloLargo: true,
            calvo: false,
            llevaCasco: false,
            llevaCapa: false,
            trajeMetalico: false,
            alas: false,
            ropaNegra: false,
            esVengador: true,
            SpiderMan: false,
            esGuardianGalaxia: false,
            esVillano: false,
            esAnimal: false,
            esJoven: false
        }
    },
    {
        id: 26,
        nombre: "Ned",
        imagen: "./Recursos/Personajes/ned.png",
        atributos: {
            esHumano: true,
            esExtraterrestre: false,
            esRobot: false,
            esHombre: true,
            tienePoderesSobrenaturales: false,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: false,
            pielMorena: true,

            barbaBigote: false,
            cabelloLargo: false,
            calvo: false,
            llevaCasco: false,
            llevaCapa: false,
            trajeMetalico: false,
            alas: false,
            ropaNegra: false,
            esVengador: false,
            SpiderMan: true,
            esGuardianGalaxia: false,
            esVillano: false,
            esAnimal: false,
            esJoven: true
        }
    },
    {
        id: 27,
        nombre: "Loki",
        imagen: "./Recursos/Personajes/loki.png",
        atributos: {
            esHumano: false,
            esExtraterrestre: true,
            esRobot: false,
            esHombre: true,
            tienePoderesSobrenaturales: true,
            tieneHabilidadesTecnologicas: false,
            pielNoHumana: false,
            pielMorena: false,

            barbaBigote: false,
            cabelloLargo: true,
            calvo: false,
            llevaCasco: false,
            llevaCapa: false,
            trajeMetalico: false,
            alas: false,
            ropaNegra: false,
            esVengador: true,
            SpiderMan: false,
            esGuardianGalaxia: false,
            esVillano: true,
            esAnimal: false,
            esJoven: false
        }
    },
];

export default characters;